global:
  # Use an existing SMTP server or a service like Mailgun or SendGrid
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'dagint@gmail.com'
  smtp_auth_username: 'dagint@gmail.com'
  smtp_auth_password: 'manhilpabsuvmyek'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-receiver'

receivers:
  - name: 'email-receiver'
    email_configs:
      - to: 'dagint@gmail.com'
